# Generated by Django 3.1.3 on 2020-11-14 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(help_text='Dias do evento', verbose_name='Dias do evento')),
                ('start_time', models.TimeField(help_text='Hora inicial', verbose_name='Hora inicial')),
                ('end_time', models.TimeField(help_text='Hora final', verbose_name='Hora final')),
                ('notes', models.TextField(blank=True, help_text='TAnotações', null=True, verbose_name='Anotações')),
            ],
            options={
                'verbose_name': 'Calendário',
                'verbose_name_plural': 'Calendários',
            },
        ),
    ]
