# Generated by Django 3.1.3 on 2020-11-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configuracao', '0002_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
