# Generated by Django 3.1 on 2021-01-07 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'Calendário', 'verbose_name_plural': 'Calendário'},
        ),
    ]
