# Generated by Django 3.1 on 2020-11-08 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0002_especializacao_profissionais_servicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profissionais',
            name='especializacao',
        ),
        migrations.RemoveField(
            model_name='profissionais',
            name='servico',
        ),
        migrations.AddField(
            model_name='especializacao',
            name='profissional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplicacao.profissionais'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicos',
            name='profissional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplicacao.profissionais'),
            preserve_default=False,
        ),
    ]
