# Generated by Django 3.1 on 2020-11-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0003_auto_20201108_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='especializacao',
            options={'verbose_name': 'Especialização', 'verbose_name_plural': 'Especializações'},
        ),
        migrations.AlterModelOptions(
            name='profissionais',
            options={'verbose_name': 'Profissional', 'verbose_name_plural': 'Profissionais'},
        ),
        migrations.AlterModelOptions(
            name='servicos',
            options={'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
    ]
