# Generated by Django 3.1 on 2020-11-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0006_auto_20201114_1842'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.clientes')),
                ('servico', models.ManyToManyField(to='aplicacao.Servicos')),
            ],
            options={
                'verbose_name': 'Agenda de Serviço',
                'verbose_name_plural': 'Agenda de Serviços',
            },
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
