# Generated by Django 3.1 on 2020-12-05 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0007_auto_20201121_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaservico',
            name='profissional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='aplicacao.profissionais'),
            preserve_default=False,
        ),
    ]
