# Generated by Django 3.1 on 2021-01-16 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0008_agendaservico_profissional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_moeda', models.CharField(blank=True, choices=[('DINHEIRO', 'Dinheiro'), ('CARTÂO_DEBITO', 'Cartão Débito'), ('CARTÂO_CREDITO', 'Cartão Crédito'), ('CHEQUE', 'Cheque')], default='PENDENTE', max_length=30, null=True)),
                ('data', models.DateTimeField(auto_now=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.agendaservico')),
            ],
        ),
    ]
