# Generated by Django 3.1 on 2021-01-16 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0009_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.pagamento')),
            ],
        ),
    ]
