# Generated by Django 3.1 on 2021-01-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0010_caixa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicos',
            options={'ordering': ['nome'], 'verbose_name': 'Serviço', 'verbose_name_plural': 'Serviços'},
        ),
        migrations.AddField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
