# Generated by Django 3.1 on 2021-01-25 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0012_auto_20210123_1135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='pagamento',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacao.caixa'),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateField(),
        ),
    ]
