# Generated by Django 3.1 on 2021-01-25 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0013_auto_20210125_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='efetuado',
            field=models.BooleanField(default=False),
        ),
    ]
