# Generated by Django 3.1 on 2021-01-30 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0014_pagamento_efetuado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_custo', models.DecimalField(decimal_places=3, max_digits=10)),
                ('valor_venda', models.DecimalField(decimal_places=3, max_digits=10)),
                ('quantidade', models.IntegerField()),
            ],
        ),
    ]
