# Generated by Django 3.1 on 2021-01-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0016_produto_agenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='agenda',
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor_custo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor_venda',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
