# Generated by Django 3.1 on 2021-01-30 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0018_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacao.agendaservico'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.produto'),
        ),
    ]
