# Generated by Django 3.1.4 on 2021-08-07 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0019_auto_20210130_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientes',
            options={'ordering': ('nome',), 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='especializacao',
            options={'ordering': ('nome',), 'verbose_name': 'Especialização', 'verbose_name_plural': 'Especializações'},
        ),
        migrations.AlterModelOptions(
            name='profissionais',
            options={'ordering': ('nome',), 'verbose_name': 'Profissional', 'verbose_name_plural': 'Profissionais'},
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='tipo_moeda',
            field=models.CharField(blank=True, choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix'), ('CARTÂO_DEBITO', 'Cartão Débito'), ('CARTÂO_CREDITO', 'Cartão Crédito'), ('CHEQUE', 'Cheque')], default='PENDENTE', max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Comissoes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('caixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='aplicacao.caixa')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aplicacao.profissionais')),
            ],
        ),
    ]
