# Generated by Django 3.1.4 on 2021-09-18 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0020_auto_20210807_1150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comissoes',
            options={'ordering': ['profissional'], 'verbose_name': 'Comissão', 'verbose_name_plural': 'Comissões'},
        ),
        migrations.AddField(
            model_name='comissoes',
            name='agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacao.agendaservico'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='tipo_moeda',
            field=models.CharField(blank=True, choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix'), ('CARTÂO_DEBITO', 'Cartão Débito'), ('CARTÂO_CREDITO', 'Cartão Crédito'), ('CHEQUE', 'Cheque')], default='DINHEIRO', max_length=30, null=True),
        ),
    ]
