# Generated by Django 3.1.4 on 2021-10-09 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0021_auto_20210918_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicos',
            name='profissional',
        ),
    ]
