# Generated by Django 3.1.4 on 2021-10-29 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0024_relatorios_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorios',
            name='profissional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='aplicacao.profissionais'),
        ),
    ]
