# Generated by Django 3.1.4 on 2021-10-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0025_relatorios_profissional'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorios',
            name='valor_comissao',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
