# Generated by Django 3.1.4 on 2021-11-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacao', '0026_relatorios_valor_comissao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comissoes',
            name='data',
            field=models.DateField(auto_now=True),
        ),
    ]
